import type { ProviderConfig } from "@/types/modelProvider";

export const DEFAULT_PROVIDER_CATALOG: ProviderConfig[] = [
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeyRef: "env:OPENAI_API_KEY",
    defaultModel: "gpt-4o-mini",
    availableModels: [
      {
        id: "gpt-4o-mini",
        label: "GPT-4o mini",
        contextWindowTokens: 128000,
        supportsStreaming: true,
        supportsToolCalling: true,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: true,
      modelListing: true,
      tokenCostEstimate: true,
    },
    contextWindowTokens: 128000,
    isLocal: false,
    enabled: true,
    securityLevel: "byok",
    healthStatus: "unknown",
    notes: "Official OpenAI adapter should stay separate from generic OpenAI-compatible endpoints.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    apiKeyRef: "env:ANTHROPIC_API_KEY",
    defaultModel: "claude-haiku-4.5",
    availableModels: [
      {
        id: "claude-haiku-4.5",
        label: "Claude Haiku 4.5",
        contextWindowTokens: 200000,
        supportsStreaming: true,
        supportsToolCalling: true,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: true,
      modelListing: false,
      tokenCostEstimate: true,
    },
    contextWindowTokens: 200000,
    isLocal: false,
    enabled: true,
    securityLevel: "byok",
    healthStatus: "unknown",
  },
  {
    id: "openai-compatible",
    name: "OpenAI-compatible endpoint",
    type: "openai-compatible",
    baseUrl: "https://example-provider.invalid/v1",
    apiKeyRef: "env:OPENAI_COMPATIBLE_API_KEY",
    defaultModel: "provider/model-id",
    availableModels: [
      {
        id: "provider/model-id",
        label: "Provider model ID",
        supportsStreaming: false,
        supportsToolCalling: false,
      },
    ],
    capabilities: {
      streaming: false,
      toolCalling: false,
      modelListing: false,
      tokenCostEstimate: false,
    },
    isLocal: false,
    enabled: false,
    securityLevel: "byok",
    healthStatus: "not_configured",
    notes: "Capability flags must be configured per endpoint; do not assume full OpenAI feature parity.",
  },
  {
    id: "ollama",
    name: "Ollama local",
    type: "ollama",
    baseUrl: "http://localhost:11434",
    defaultModel: "qwen2.5-coder:7b",
    availableModels: [
      {
        id: "qwen2.5-coder:7b",
        label: "Qwen 2.5 Coder 7B",
        supportsStreaming: true,
        supportsToolCalling: false,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: false,
      modelListing: true,
      tokenCostEstimate: false,
    },
    isLocal: true,
    enabled: true,
    securityLevel: "local",
    healthStatus: "unknown",
    notes: "Use native /api/tags for discovery and keep OpenAI-compatible /v1 calls behind capability checks.",
  },
  {
    id: "cloud-placeholder",
    name: "Cloud provider placeholder",
    type: "cloud",
    availableModels: [],
    capabilities: {
      streaming: false,
      toolCalling: false,
      modelListing: false,
      tokenCostEstimate: false,
    },
    isLocal: false,
    enabled: false,
    securityLevel: "enterprise",
    healthStatus: "not_configured",
    notes: "Reserved for Azure, Bedrock, Vertex, or managed gateways after adapter boundaries are stable.",
  },
  {
    id: "ollama-remote",
    name: "Ollama remote endpoint",
    type: "ollama-remote",
    baseUrl: "https://your-ollama-host:11434", // placeholder — user must configure
    apiKeyRef: "env:OLLAMA_REMOTE_API_KEY",    // optional — only needed behind authenticated reverse proxies
    defaultModel: "qwen2.5-coder:7b",
    availableModels: [
      {
        id: "qwen2.5-coder:7b",
        label: "Qwen 2.5 Coder 7B (remote)",
        supportsStreaming: true,
        supportsToolCalling: false,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: false,
      modelListing: true,
      tokenCostEstimate: false,
    },
    isLocal: false,
    enabled: false,
    securityLevel: "hosted",
    healthStatus: "not_configured",
    notes: "Remote Ollama endpoint. Does NOT have local-only privacy. Treat like a cloud provider for data governance. Auth may require a reverse proxy.",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    type: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyRef: "env:GEMINI_API_KEY",
    defaultModel: "gemini-2.0-flash",
    availableModels: [
      {
        id: "gemini-2.0-flash",
        label: "Gemini 2.0 Flash",
        contextWindowTokens: 1000000,
        supportsStreaming: true,
        supportsToolCalling: true,
      },
      {
        id: "gemini-1.5-pro",
        label: "Gemini 1.5 Pro",
        contextWindowTokens: 2000000,
        supportsStreaming: true,
        supportsToolCalling: true,
      },
      {
        id: "gemini-1.5-flash",
        label: "Gemini 1.5 Flash",
        contextWindowTokens: 1000000,
        supportsStreaming: true,
        supportsToolCalling: true,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: true,
      modelListing: true,
      tokenCostEstimate: false,
    },
    contextWindowTokens: 1000000,
    isLocal: false,
    enabled: false,
    securityLevel: "byok",
    healthStatus: "not_configured",
    notes: "Gemini uses a separate API format (NOT OpenAI-compatible). A dedicated Gemini adapter is required. Do not route Gemini through the OpenAI-compatible adapter without verification.",
  },
  {
    id: "kilo",
    name: "Kilo / Kilo Gateway placeholder",
    type: "kilo",
    baseUrl: "https://api.kilo.ai/api/gateway",
    apiKeyRef: "env:KILO_API_KEY",
    defaultModel: "anthropic/claude-sonnet-4.5",
    availableModels: [
      {
        id: "anthropic/claude-sonnet-4.5",
        label: "Claude Sonnet via Kilo Gateway",
        supportsStreaming: true,
        supportsToolCalling: true,
      },
    ],
    capabilities: {
      streaming: true,
      toolCalling: true,
      modelListing: true,
      tokenCostEstimate: true,
    },
    isLocal: false,
    enabled: false,
    securityLevel: "hosted",
    healthStatus: "not_configured",
    notes: "Treat Kilo as a gateway-compatible integration target; do not invent private Kilo Code APIs.",
  },
];

export function getProviderById(id: string): ProviderConfig | undefined {
  return DEFAULT_PROVIDER_CATALOG.find((provider) => provider.id === id);
}
