"""
CrewAI export — Harness Studio — Active Project
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install crewai crewai-tools python-dotenv
"""
from __future__ import annotations
import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from crewai_tools import (
    FileReadTool, FileWriteTool, DirectoryReadTool, WebsiteSearchTool,
)

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local


# ── Tool registry ──────────────────────────────────────────────────────
file_read    = FileReadTool()
file_write   = FileWriteTool()
dir_read     = DirectoryReadTool()
web_search   = WebsiteSearchTool()

# ── LLM definitions ────────────────────────────────────────────────────
llm_claude_opus_46 = LLM(model="anthropic/claude-opus-4-6")
llm_claude_haiku_45 = LLM(model="anthropic/claude-haiku-4-5")
llm_claude_sonnet_46 = LLM(model="anthropic/claude-sonnet-4-6")

# ── Agent definitions ──────────────────────────────────────────────────
project_orchestrator = Agent(
    role="Orchestrator",
    goal="Project Orchestrator: Reads PROJECT_STATUS.md + TODO.md, selects highest-priority task, routes to Task Router.",
    backstory="""Orchestrator agent responsible for Reads PROJECT_STATUS.md + TODO.md, selects highest-priority task, routes to Task Router.""",
    tools=[file_read, dir_read],
    llm=llm_claude_opus_46,
    verbose=True,
    allow_delegation=true,
    max_iter=20,
)

task_router = Agent(
    role="Gateway",
    goal="Task Router: Classifies task into domain (ui/rust/test/doc/mixed) and routes to appropriate workers.",
    backstory="""Classify the task into ui/rust/test/doc/mixed. Output JSON with domain and rationale.""",
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=5,
)

frontend_worker = Agent(
    role="Worker",
    goal="Frontend Worker: React/TypeScript changes. Atelier design tokens. No hex colors. IPC through tauriCommands.ts.",
    backstory="""Implement React/TypeScript changes following Atelier design system. CSS vars only, NodeIcon for icons, state in Zustand. Run tsc --noEmit after each file.""",
    tools=[file_read, file_write, dir_read],
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=40,
)

backend_worker = Agent(
    role="Worker",
    goal="Backend Worker: Rust/Tauri backend. resolve_safe_path(), atomic writes, AppError, cargo build after changes.",
    backstory="""Implement Rust/Tauri changes. Always use resolve_safe_path(). Atomic writes only. Register commands in lib.rs. Run cargo build after each file.""",
    tools=[file_read, file_write, dir_read],
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=30,
)

test_worker = Agent(
    role="Worker",
    goal="Test Worker: Writes Vitest + Rust tests for changed code. Runs full suite. Reports pass/fail counts.",
    backstory="""Write tests for changed code. Run npx vitest run and cargo test. Report N/M passing. Only mark done when all pass.""",
    tools=[file_read, file_write, dir_read],
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=20,
)

visual_inspector = Agent(
    role="Critic",
    goal="Visual Inspector: Reviews frontend changes against Atelier design system. Checks CSS tokens, spacing, dark theme, node anatomy.",
    backstory="""Review frontend changes for Atelier compliance: CSS vars, dark theme, spacing grid, node anatomy (header/prompt/footer/token bar). Return APPROVED or REVISE with specific fixes.""",
    tools=[file_read],
    llm=llm_claude_sonnet_46,
    verbose=True,
    allow_delegation=false,
    max_iter=10,
)

code_critic = Agent(
    role="Critic",
    goal="Code Critic: Architecture + security + quality gate. Returns APPROVED, REVISE, or ESCALATE.",
    backstory="""Review for: architecture (Zustand state, typed IPC, file size ≤300 lines), security (no keys in code, path traversal, hook consent), code quality (no any, error handling, no TODOs). Return APPROVED / REVISE / ESCALATE.""",
    tools=[file_read, dir_read],
    llm=llm_claude_opus_46,
    verbose=True,
    allow_delegation=false,
    max_iter=12,
)

documentation_worker = Agent(
    role="Worker",
    goal="Documentation Worker: Updates PROJECT_STATUS.md, DEVELOPMENT_LOG.md, CHANGELOG.md after each approved cycle.",
    backstory="""Update docs after successful cycle. Follow existing format exactly. Update status, log entry, changelog.""",
    tools=[file_read, file_write],
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=10,
)

# ── Task definitions ────────────────────────────────────────────────────
task_project_orchestrator = Task(
    description="Project Orchestrator: Reads PROJECT_STATUS.md + TODO.md, selects highest-priority task, routes to Task Router.",
    expected_output="Structured output from Project Orchestrator",
    agent=project_orchestrator,
    context=[task_rate_limit_sentinel],
)

task_task_router = Task(
    description="Task Router: Classifies task into domain (ui/rust/test/doc/mixed) and routes to appropriate workers.",
    expected_output="Structured output from Task Router",
    agent=task_router,
    context=[task_project_orchestrator],
)

task_frontend_worker = Task(
    description="Frontend Worker: React/TypeScript changes. Atelier design tokens. No hex colors. IPC through tauriCommands.ts.",
    expected_output="Structured output from Frontend Worker",
    agent=frontend_worker,
    context=[task_task_router],
)

task_backend_worker = Task(
    description="Backend Worker: Rust/Tauri backend. resolve_safe_path(), atomic writes, AppError, cargo build after changes.",
    expected_output="Structured output from Backend Worker",
    agent=backend_worker,
    context=[task_task_router],
)

task_test_worker = Task(
    description="Test Worker: Writes Vitest + Rust tests for changed code. Runs full suite. Reports pass/fail counts.",
    expected_output="Structured output from Test Worker",
    agent=test_worker,
    context=[task_task_router],
)

task_visual_inspector = Task(
    description="Visual Inspector: Reviews frontend changes against Atelier design system. Checks CSS tokens, spacing, dark theme, node anatomy.",
    expected_output="Structured output from Visual Inspector",
    agent=visual_inspector,
    context=[task_test_gate],
)

task_code_critic = Task(
    description="Code Critic: Architecture + security + quality gate. Returns APPROVED, REVISE, or ESCALATE.",
    expected_output="Structured output from Code Critic",
    agent=code_critic,
    context=[task_visual_inspector],
)

task_documentation_worker = Task(
    description="Documentation Worker: Updates PROJECT_STATUS.md, DEVELOPMENT_LOG.md, CHANGELOG.md after each approved cycle.",
    expected_output="Structured output from Documentation Worker",
    agent=documentation_worker,
    context=[task_task_router, task_code_critic],
)

# ── Crew assembly ───────────────────────────────────────────────────────
crew = Crew(
    agents=[project_orchestrator, task_router, frontend_worker, backend_worker, test_worker, visual_inspector, code_critic, documentation_worker],
    tasks=[task_project_orchestrator, task_task_router, task_frontend_worker, task_backend_worker, task_test_worker, task_visual_inspector, task_code_critic, task_documentation_worker],
    process=Process.hierarchical,
    manager_agent=project_orchestrator,
    verbose=True,
    memory=True,
)

# ── Entry point ────────────────────────────────────────────────────────
if __name__ == '__main__':
    result = crew.kickoff(inputs={
        "query": "Initial task for Harness Studio — Active Project"
    })
    print(result)