"""
LangGraph export — Harness Studio — Active Project
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install langgraph langchain-anthropic python-dotenv
"""
from __future__ import annotations
import os
from typing import TypedDict, Annotated, Sequence
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_anthropic import ChatAnthropic
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local

# ── Shared workflow state ──────────────────────────────────────────────
class WorkflowState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], lambda a, b: list(a) + list(b)]
    current_goal: str  # memory key: current-goal
    test_results: str  # memory key: test-results
    review_verdict: str  # memory key: review-verdict
    visual_verdict: str  # memory key: visual-verdict
    dev_history: str  # memory key: dev-history
    task_plan: str  # memory key: task-plan
    orchestrator_context: str  # memory key: orchestrator-context
    routing_decision: str  # memory key: routing-decision
    frontend_changes: str  # memory key: frontend-changes
    impl_status: str  # memory key: impl-status
    backend_changes: str  # memory key: backend-changes
    docs_updated: str  # memory key: docs-updated
    codebase_map: str  # memory key: codebase-map
    gate_result: str  # memory key: gate-result
    rate_limit_status: str  # memory key: rate-limit-status

# ── Model registry ────────────────────────────────────────────────────
claude_opus_46 = ChatAnthropic(model="claude-opus-4-6", temperature=0.7)
claude_haiku_45 = ChatAnthropic(model="claude-haiku-4-5", temperature=0.7)
claude_sonnet_46 = ChatAnthropic(model="claude-sonnet-4-6", temperature=0.7)

# ── Agent node functions ───────────────────────────────────────────────
def project_orchestrator(state: WorkflowState) -> WorkflowState:
    """Orchestrator: Reads PROJECT_STATUS.md + TODO.md, selects highest-priority task, routes to Task Router."""
    # Load prompt from file: 
    with open("") as f:
        system_prompt = f.read()

    response = claude_opus_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def task_router(state: WorkflowState) -> WorkflowState:
    """Gateway: Classifies task into domain (ui/rust/test/doc/mixed) and routes to appropriate workers."""
    # Gateway — routes based on condition
    # Condition: domain in {ui, rust, test, doc, mixed}
    # This function returns routing key, not state
    last_msg = state['messages'][-1] if state['messages'] else None
    # TODO: implement routing logic
    return 'default'  # return the name of the next node

def frontend_worker(state: WorkflowState) -> WorkflowState:
    """Worker: React/TypeScript changes. Atelier design tokens. No hex colors. IPC through tauriCommands.ts."""
    system_prompt = """Implement React/TypeScript changes following Atelier design system. CSS vars only, NodeIcon for icons, state in Zustand. Run tsc --noEmit after each file."""

    response = claude_haiku_45.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def backend_worker(state: WorkflowState) -> WorkflowState:
    """Worker: Rust/Tauri backend. resolve_safe_path(), atomic writes, AppError, cargo build after changes."""
    system_prompt = """Implement Rust/Tauri changes. Always use resolve_safe_path(). Atomic writes only. Register commands in lib.rs. Run cargo build after each file."""

    response = claude_haiku_45.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def test_worker(state: WorkflowState) -> WorkflowState:
    """Worker: Writes Vitest + Rust tests for changed code. Runs full suite. Reports pass/fail counts."""
    system_prompt = """Write tests for changed code. Run npx vitest run and cargo test. Report N/M passing. Only mark done when all pass."""

    response = claude_haiku_45.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def visual_inspector(state: WorkflowState) -> WorkflowState:
    """Critic: Reviews frontend changes against Atelier design system. Checks CSS tokens, spacing, dark theme, node anatomy."""
    system_prompt = """Review frontend changes for Atelier compliance: CSS vars, dark theme, spacing grid, node anatomy (header/prompt/footer/token bar). Return APPROVED or REVISE with specific fixes."""

    response = claude_sonnet_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def code_critic(state: WorkflowState) -> WorkflowState:
    """Critic: Architecture + security + quality gate. Returns APPROVED, REVISE, or ESCALATE."""
    system_prompt = """Review for: architecture (Zustand state, typed IPC, file size ≤300 lines), security (no keys in code, path traversal, hook consent), code quality (no any, error handling, no TODOs). Return APPROVED / REVISE / ESCALATE."""

    response = claude_opus_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def documentation_worker(state: WorkflowState) -> WorkflowState:
    """Worker: Updates PROJECT_STATUS.md, DEVELOPMENT_LOG.md, CHANGELOG.md after each approved cycle."""
    system_prompt = """Update docs after successful cycle. Follow existing format exactly. Update status, log entry, changelog."""

    response = claude_haiku_45.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def codebase_memory(state: WorkflowState) -> WorkflowState:
    """Memory: Persists codebase map (key files, types, patterns) across sessions. Path .harness/memory/codebase.jsonl."""
    # Memory node — reads/writes persistent state
    # TODO: write to memory key 'codebase-map'
    return state

def progress_log(state: WorkflowState) -> WorkflowState:
    """Memory: Append-only journal of every dev cycle. Enables multi-session continuity. Path .harness/dev-progress.jsonl."""
    # Memory node — reads/writes persistent state
    # TODO: write to memory key 'dev-history'
    return state

def test_gate(state: WorkflowState) -> WorkflowState:
    """Hook: Runs tsc + vitest + cargo test before inspectors. Blocks on any failure."""
    # Hook node — runs pre/post execution logic
    # Pre-hook: .harness/hooks/test_gate.sh
    return state

def rate_limit_sentinel(state: WorkflowState) -> WorkflowState:
    """Hook: Checks .harness/state/rate_limit.json. Sets CLAUDE_RATE_LIMITED=1 if Anthropic is limited so workers use fallback models."""
    # Hook node — runs pre/post execution logic
    # Pre-hook: .harness/hooks/rate_limit_sentinel.py
    return state

# ── Graph definition ───────────────────────────────────────────────────
def build_graph() -> StateGraph:
    g = StateGraph(WorkflowState)

    g.add_node("project_orchestrator", project_orchestrator)
    g.add_node("frontend_worker", frontend_worker)
    g.add_node("backend_worker", backend_worker)
    g.add_node("test_worker", test_worker)
    g.add_node("visual_inspector", visual_inspector)
    g.add_node("code_critic", code_critic)
    g.add_node("documentation_worker", documentation_worker)
    g.add_node("codebase_memory", codebase_memory)
    g.add_node("progress_log", progress_log)
    g.add_node("test_gate", test_gate)
    g.add_node("rate_limit_sentinel", rate_limit_sentinel)

    g.add_edge("project_orchestrator", "task_router")
    # Gateway routing: Task Router → Frontend Worker (ui?)
    # g.add_conditional_edges("...", task_router, {"ui?": "frontend_worker"})
    # Gateway routing: Task Router → Backend Worker (rust?)
    # g.add_conditional_edges("...", task_router, {"rust?": "backend_worker"})
    # Gateway routing: Task Router → Test Worker (test?)
    # g.add_conditional_edges("...", task_router, {"test?": "test_worker"})
    # Gateway routing: Task Router → Documentation Worker (doc?)
    # g.add_conditional_edges("...", task_router, {"doc?": "documentation_worker"})
    g.add_edge("frontend_worker", "test_gate")
    g.add_edge("backend_worker", "test_gate")
    g.add_edge("test_worker", "test_gate")
    g.add_edge("test_gate", "visual_inspector")
    g.add_edge("visual_inspector", "code_critic")
    g.add_edge("code_critic", "documentation_worker")
    g.add_edge("frontend_worker", "visual_inspector")  # feedback loop
    g.add_edge("frontend_worker", "code_critic")  # feedback loop
    g.add_edge("backend_worker", "code_critic")  # feedback loop
    # Memory write: frontend_worker → codebase_memory
    # Memory write: backend_worker → codebase_memory
    # Memory write: documentation_worker → progress_log
    g.add_edge("rate_limit_sentinel", "project_orchestrator")

    g.set_entry_point("project_orchestrator")
    g.add_edge("codebase_memory", END)
    g.add_edge("progress_log", END)

    checkpointer = MemorySaver()
    return g.compile(checkpointer=checkpointer)


# ── Entry point ────────────────────────────────────────────────────────
if __name__ == '__main__':
    graph = build_graph()
    result = graph.invoke(
        {"messages": [HumanMessage(content="Hello from Harness Studio — Active Project")]},
        config={"configurable": {"thread_id": "1"}},
    )
    print(result)