/**
 * AGENTS.md generator — creates the standard agent definition file
 * used by Claude Code, Codex, and other AI tools to understand
 * what each agent does and how they interact.
 */
import type { WorkflowDef } from "@/types/workflow";
import { ROLE_META } from "@/utils/nodeColors";

export function generateAgentsMd(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const now = new Date().toISOString().split("T")[0];

  const agentById = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, a]));

  const lines: string[] = [];

  lines.push(`# AGENTS.md — ${meta.name}`);
  lines.push(`_Generated by Harness Studio · ${now}_`);
  lines.push("");
  lines.push("This file describes every agent in this harness, their roles, capabilities,");
  lines.push("and how they communicate. Keep this file in sync with the workflow YAML.");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── Topology overview ──────────────────────────────────────────────────
  lines.push("## Topology overview");
  lines.push("");
  lines.push("```");
  agents.forEach((a, i) => {
    const meta2 = ROLE_META[a.role];
    const outs = connections
      .filter((c) => c.sourceAgentId === `agent-${i}`)
      .map((c) => {
        const t = agentById[c.targetAgentId];
        return t ? `→ ${t.name}${c.label ? ` (${c.label})` : ""}` : `→ ${c.targetAgentId}`;
      });
    lines.push(`${meta2.glyph} ${a.name.padEnd(20)} ${outs.join("  ") || "(terminal)"}`);
  });
  lines.push("```");
  lines.push("");

  // ── Per-agent definitions ──────────────────────────────────────────────
  lines.push("## Agent definitions");
  lines.push("");

  agents.forEach((a, i) => {
    const roleMeta = ROLE_META[a.role];
    lines.push(`### ${roleMeta.glyph} \`${a.name}\``);
    lines.push("");
    lines.push(`| Field | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| Role | ${roleMeta.label} |`);
    lines.push(`| Model | \`${a.model || "—"}\` |`);
    lines.push(`| Max tokens | ${a.maxTokens.toLocaleString()} |`);
    lines.push(`| Token budget | ${a.tokens.budget.toLocaleString()} |`);
    lines.push(`| Max steps | ${a.maxSteps} |`);
    lines.push(`| Timeout | ${a.timeoutSeconds}s |`);
    if (a.condition) lines.push(`| Condition | \`${a.condition}\` |`);
    lines.push("");

    if (a.promptSource.type === "inline" && a.promptSource.content) {
      lines.push("**System prompt:**");
      lines.push("");
      lines.push("```");
      lines.push(a.promptSource.content);
      lines.push("```");
      lines.push("");
    } else if (a.promptSource.type === "file") {
      lines.push(`**System prompt file:** \`${a.promptSource.path}\``);
      lines.push("");
    }

    if (a.tools.length > 0) {
      lines.push("**Permitted tools:**");
      a.tools.forEach((t) => lines.push(`- \`${t}\``));
      lines.push("");
    }

    if (a.preHook || a.postHook) {
      lines.push("**Hooks:**");
      if (a.preHook) {
        lines.push(`- Pre: \`${a.preHook.path}\` (consent: ${a.preHook.requireConsent})`);
      }
      if (a.postHook) {
        lines.push(`- Post: \`${a.postHook.path}\` (consent: ${a.postHook.requireConsent})`);
      }
      lines.push("");
    }

    const inputs  = connections.filter((c) => c.targetAgentId === `agent-${i}`).map((c) => agentById[c.sourceAgentId]?.name ?? c.sourceAgentId);
    const outputs = connections.filter((c) => c.sourceAgentId === `agent-${i}`).map((c) => agentById[c.targetAgentId]?.name ?? c.targetAgentId);
    if (inputs.length)  lines.push(`**Receives from:** ${inputs.join(", ")}`);
    if (outputs.length) lines.push(`**Sends to:** ${outputs.join(", ")}`);
    if (inputs.length || outputs.length) lines.push("");

    if (a.memoryRead.length || a.memoryWrite.length) {
      if (a.memoryRead.length)  lines.push(`**Reads memory:** ${a.memoryRead.map((k) => `\`${k}\``).join(", ")}`);
      if (a.memoryWrite.length) lines.push(`**Writes memory:** ${a.memoryWrite.map((k) => `\`${k}\``).join(", ")}`);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  });

  lines.push(`_Do not edit manually — regenerate via Harness Studio > Generate > AGENTS.md_`);

  return lines.join("\n");
}
