/**
 * CLAUDE.md generator — synthesizes all agent configs into a single
 * project-level instruction file readable by Claude Code.
 */
import type { WorkflowDef } from "@/types/workflow";
import { ROLE_META } from "@/utils/nodeColors";

export function generateClaudeMd(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const now = new Date().toISOString().split("T")[0];

  const roleIndex = Object.fromEntries(agents.map((a, i) => [a.name, i]));
  const outputsOf = (name: string): string[] => {
    const agentIdx = roleIndex[name];
    if (agentIdx === undefined) return [];
    return connections
      .filter((c) => c.sourceAgentId === `agent-${agentIdx}`)
      .map((c) => {
        const tgt = agents[parseInt(c.targetAgentId.replace("agent-", ""))];
        return tgt?.name ?? c.targetAgentId;
      });
  };

  const lines: string[] = [];

  lines.push(`# ${meta.name}`);
  lines.push(`_Generated by Harness Studio · ${now}_`);
  lines.push(`_Version: ${meta.version}_`);
  if (meta.description) lines.push(`\n${meta.description}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── Project context ──────────────────────────────────────────────────────
  lines.push("## Project context");
  lines.push("");
  lines.push(`This project uses a multi-agent harness with **${agents.length}** agents.`);
  lines.push(`The workflow is defined in \`.harness/${meta.name.toLowerCase().replace(/\s+/g, "-")}.harness.yaml\`.`);
  lines.push(`All config files live under \`.harness/\`. All edits should be reflected there.`);
  lines.push("");

  // ── Agent roster ─────────────────────────────────────────────────────────
  lines.push("## Agent roster");
  lines.push("");
  lines.push("| Agent | Role | Model | Tools |");
  lines.push("|---|---|---|---|");
  agents.forEach((a) => {
    const meta2 = ROLE_META[a.role];
    const tools = a.tools.length ? a.tools.slice(0, 5).join(", ") + (a.tools.length > 5 ? ` +${a.tools.length - 5}` : "") : "—";
    lines.push(`| ${meta2.glyph} **${a.name}** | ${meta2.label} | \`${a.model || "—"}\` | \`${tools}\` |`);
  });
  lines.push("");

  // ── Agent details ────────────────────────────────────────────────────────
  lines.push("## Agent responsibilities");
  lines.push("");
  agents.forEach((a) => {
    const roleMeta = ROLE_META[a.role];
    lines.push(`### ${roleMeta.glyph} ${a.name} (${roleMeta.label})`);
    if (a.description) lines.push(`> ${a.description}`);
    lines.push("");
    if (a.promptSource.type === "inline" && a.promptSource.content) {
      lines.push("**System prompt:**");
      lines.push("```");
      lines.push(a.promptSource.content.slice(0, 400) + (a.promptSource.content.length > 400 ? "\n…" : ""));
      lines.push("```");
    } else if (a.promptSource.type === "file") {
      lines.push(`**System prompt:** see \`${a.promptSource.path}\``);
    }
    lines.push("");
    if (a.tools.length > 0) {
      lines.push(`**Allowed tools:** ${a.tools.map((t) => `\`${t}\``).join(", ")}`);
    }
    const outs = outputsOf(a.name);
    if (outs.length > 0) {
      lines.push(`**Passes output to:** ${outs.join(", ")}`);
    }
    if (a.preHook || a.postHook) {
      const hooks = [a.preHook && `pre: \`${a.preHook.path}\``, a.postHook && `post: \`${a.postHook.path}\``]
        .filter(Boolean).join(", ");
      lines.push(`**Hooks:** ${hooks}`);
    }
    if (a.memoryRead.length || a.memoryWrite.length) {
      if (a.memoryRead.length) lines.push(`**Reads memory keys:** ${a.memoryRead.map((k) => `\`${k}\``).join(", ")}`);
      if (a.memoryWrite.length) lines.push(`**Writes memory keys:** ${a.memoryWrite.map((k) => `\`${k}\``).join(", ")}`);
    }
    lines.push("");
  });

  // ── Security notes ──────────────────────────────────────────────────────
  const highRiskAgents = agents.filter((a) =>
    a.tools.some((t) => ["bash", "subagent_dispatch", "fs.write"].includes(t))
  );
  if (highRiskAgents.length > 0) {
    lines.push("## Security notes");
    lines.push("");
    lines.push("The following agents have elevated permissions. Exercise caution:");
    highRiskAgents.forEach((a) => {
      const risky = a.tools.filter((t) => ["bash", "subagent_dispatch", "fs.write"].includes(t));
      lines.push(`- **${a.name}**: \`${risky.join(", ")}\``);
    });
    lines.push("");
    lines.push("All hook executions require user consent and are logged to `.harness/audit.log.jsonl`.");
    lines.push("");
  }

  // ── Execution notes ──────────────────────────────────────────────────────
  lines.push("## Execution settings");
  lines.push("");
  lines.push(`- Max parallel agents: **${def.executionSettings.maxParallel}**`);
  lines.push(`- Workflow timeout: **${def.executionSettings.timeoutSeconds}s**`);
  lines.push(`- Retry on failure: **${def.executionSettings.retryOnFailure}**`);
  lines.push("");
  lines.push("---");
  lines.push(`_Do not edit this file manually — regenerate via Harness Studio > Generate > CLAUDE.md_`);

  return lines.join("\n");
}
