/**
 * CrewAI Python export — generates a runnable CrewAI crew that
 * mirrors the visual workflow definition.
 */
import type { WorkflowDef } from "@/types/workflow";
import { AgentRole } from "@/types/agent";
import { ROLE_META } from "@/utils/nodeColors";

function toPythonId(name: string): string {
  return name.toLowerCase().replace(/[\s\-]/g, "_").replace(/[^a-z0-9_]/g, "");
}

function indent(n: number, s: string): string {
  return " ".repeat(n * 4) + s;
}

export function generateCrewAi(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const agentById = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, a]));

  // Filter out non-AI nodes (hooks, memory) for CrewAI agent roster
  const aiAgents = agents.filter((a) =>
    a.role !== AgentRole.Hook && a.role !== AgentRole.Memory
  );
  // Process type: sequential if linear, parallel if fan-out
  const isParallel = agents.some((a) => a.role === AgentRole.Gateway || a.role === AgentRole.Aggregator);
  const process = isParallel ? "Process.hierarchical" : "Process.sequential";

  const lines: string[] = [];

  // Header
  lines.push(`"""
CrewAI export — ${meta.name}
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install crewai crewai-tools python-dotenv
"""
from __future__ import annotations
import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, ${isParallel ? "Process, LLM" : "Process, LLM"}
from crewai_tools import (
    FileReadTool, FileWriteTool, DirectoryReadTool, WebsiteSearchTool,
)

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local

`);

  // ── Tool registry ──────────────────────────────────────────────────────
  lines.push("# ── Tool registry ──────────────────────────────────────────────────────");
  lines.push("file_read    = FileReadTool()");
  lines.push("file_write   = FileWriteTool()");
  lines.push("dir_read     = DirectoryReadTool()");
  lines.push("web_search   = WebsiteSearchTool()");
  lines.push("");

  // ── LLM definitions ───────────────────────────────────────────────────
  const uniqueModels = [...new Set(aiAgents.filter((a) => a.model).map((a) => a.model))];
  if (uniqueModels.length > 0) {
    lines.push("# ── LLM definitions ────────────────────────────────────────────────────");
    uniqueModels.forEach((model) => {
      const varName = `llm_${toPythonId(model)}`;
      const provider = model.startsWith("claude") ? "anthropic" : "openai";
      lines.push(`${varName} = LLM(model="${provider}/${model.replace(".", "-")}")`);
    });
    lines.push("");
  }

  // ── Agent definitions ──────────────────────────────────────────────────
  lines.push("# ── Agent definitions ──────────────────────────────────────────────────");
  aiAgents.forEach((a) => {
    const varName = toPythonId(a.name);
    const modelVar = a.model ? `llm_${toPythonId(a.model)}` : "None";
    const roleMeta = ROLE_META[a.role];

    const systemPrompt = a.promptSource.type === "inline" && a.promptSource.content
      ? a.promptSource.content.replace(/"""/g, "'''").slice(0, 300) + (a.promptSource.content.length > 300 ? "..." : "")
      : `${roleMeta.label} agent responsible for ${a.description || a.name}`;

    // Map tool permissions to CrewAI tools
    const toolVars: string[] = [];
    if (a.tools.some((t) => t.includes("read_file") || t.includes("fs.read"))) toolVars.push("file_read");
    if (a.tools.some((t) => t.includes("fs.write") || t.includes("write_file"))) toolVars.push("file_write");
    if (a.tools.some((t) => t.includes("list_files"))) toolVars.push("dir_read");
    if (a.tools.some((t) => t.includes("web_search") || t.includes("web_fetch"))) toolVars.push("web_search");

    lines.push(`${varName} = Agent(`);
    lines.push(indent(1, `role="${roleMeta.label}",`));
    lines.push(indent(1, `goal="${a.name}: ${a.description || systemPrompt.split(".")[0]}",`));
    lines.push(indent(1, `backstory="""${systemPrompt}""",`));
    if (toolVars.length > 0) {
      lines.push(indent(1, `tools=[${toolVars.join(", ")}],`));
    }
    if (a.model) {
      lines.push(indent(1, `llm=${modelVar},`));
    }
    lines.push(indent(1, `verbose=True,`));
    lines.push(indent(1, `allow_delegation=${a.role === AgentRole.Orchestrator},`));
    lines.push(indent(1, `max_iter=${a.maxSteps},`));
    lines.push(")");
    lines.push("");
  });

  // ── Task definitions ───────────────────────────────────────────────────
  lines.push("# ── Task definitions ────────────────────────────────────────────────────");
  aiAgents.forEach((a) => {
    const agentVar = toPythonId(a.name);
    const taskVar  = `task_${agentVar}`;

    // find context tasks (agents that feed into this one)
    const feedingAgents = connections
      .filter((c) => {
        const tgt = agentById[c.targetAgentId];
        return tgt?.name === a.name && c.edgeKind !== "feedback" && c.edgeKind !== "memory";
      })
      .map((c) => {
        const src = agentById[c.sourceAgentId];
        return src ? `task_${toPythonId(src.name)}` : null;
      })
      .filter(Boolean) as string[];

    lines.push(`${taskVar} = Task(`);
    lines.push(indent(1, `description="${a.name}: ${a.description || ROLE_META[a.role].label + " task"}",`));
    lines.push(indent(1, `expected_output="Structured output from ${a.name}",`));
    lines.push(indent(1, `agent=${agentVar},`));
    if (feedingAgents.length > 0) {
      lines.push(indent(1, `context=[${feedingAgents.join(", ")}],`));
    }
    lines.push(")");
    lines.push("");
  });

  // ── Crew assembly ──────────────────────────────────────────────────────
  const allAgentVars = aiAgents.map((a) => toPythonId(a.name));
  const allTaskVars  = aiAgents.map((a) => `task_${toPythonId(a.name)}`);

  // Orchestrator is the manager if it exists
  const orchestrator = aiAgents.find((a) => a.role === AgentRole.Orchestrator);

  lines.push("# ── Crew assembly ───────────────────────────────────────────────────────");
  lines.push("crew = Crew(");
  lines.push(indent(1, `agents=[${allAgentVars.join(", ")}],`));
  lines.push(indent(1, `tasks=[${allTaskVars.join(", ")}],`));
  lines.push(indent(1, `process=${process},`));
  if (isParallel && orchestrator) {
    lines.push(indent(1, `manager_agent=${toPythonId(orchestrator.name)},`));
  }
  lines.push(indent(1, "verbose=True,"));
  lines.push(indent(1, "memory=True,"));
  lines.push(")");
  lines.push("");

  // ── Entry point ────────────────────────────────────────────────────────
  lines.push("# ── Entry point ────────────────────────────────────────────────────────");
  lines.push("if __name__ == '__main__':");
  lines.push(indent(1, "result = crew.kickoff(inputs={"));
  lines.push(indent(2, `"query": "Initial task for ${meta.name}"`));
  lines.push(indent(1, "})"));
  lines.push(indent(1, "print(result)"));

  return lines.join("\n");
}
