/**
 * CrewAI Python export — generates a runnable CrewAI crew that
 * mirrors the visual workflow definition.
 */
import type { WorkflowDef } from "@/types/workflow";
import { AgentRole } from "@/types/agent";
import { ROLE_META } from "@/utils/nodeColors";

// Python's keyword.kwlist — none of these can be used as a variable name.
const PY_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
  "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
  "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
]);

// Module-level names the template below binds or calls; generated names must not shadow them.
const RESERVED_NAMES = [
  "annotations", "os", "load_dotenv", "file_read", "file_write", "dir_read", "web_search", "crew", "result", "print",
];

/** Python identifier for `name`; empty, digit-leading or keyword results get `prefix`. */
function toPythonId(name: string, prefix: string): string {
  const id = name.toLowerCase().replace(/[\s\-]/g, "_").replace(/[^a-z0-9_]/g, "");
  if (!id) return prefix;
  return /^\d/.test(id) || PY_KEYWORDS.has(id) ? `${prefix}_${id}` : id;
}

function indent(n: number, s: string): string {
  return " ".repeat(n * 4) + s;
}

/** Hands out unique identifiers (numeric suffix on collision) so every reference uses one mapped name. */
function pythonIdAllocator(reserved: string[]): (name: string, prefix: string) => string {
  const used = new Set(reserved);
  return (name, prefix) => {
    const base = toPythonId(name, prefix);
    let id = base;
    for (let n = 2; used.has(id); n++) id = `${base}_${n}`;
    used.add(id);
    return id;
  };
}

/** Agent ids in dependency order (feedback edges excluded); ties and cycles keep canvas order. */
function dependencyOrder(def: WorkflowDef): string[] {
  const ids = def.agents.map((_, i) => `agent-${i}`);
  const deps = def.connections.filter((c) => c.edgeKind !== "feedback");
  const order: string[] = [];
  while (order.length < ids.length) {
    const pending = ids.filter((id) => !order.includes(id));
    const ready = pending.find((id) =>
      deps.every((c) => c.targetAgentId !== id || order.includes(c.sourceAgentId))
    );
    order.push(ready ?? pending[0]);
  }
  return order;
}

export function generateCrewAi(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const agentById = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, a]));

  // Filter out non-AI nodes (hooks, memory) for CrewAI agent roster
  const aiIds = Object.keys(agentById).filter((id) =>
    agentById[id].role !== AgentRole.Hook && agentById[id].role !== AgentRole.Memory
  );
  // Process type: sequential if linear, parallel if fan-out
  const isParallel = agents.some((a) => a.role === AgentRole.Gateway || a.role === AgentRole.Aggregator);
  const process = isParallel ? "Process.hierarchical" : "Process.sequential";

  // Every Python name is allocated once, here, so all references agree.
  const pyId = pythonIdAllocator(RESERVED_NAMES);
  const agentVar = Object.fromEntries(aiIds.map((id) => [id, pyId(agentById[id].name, "agent")]));
  const taskVar = Object.fromEntries(aiIds.map((id) => [id, pyId(`task_${agentVar[id]}`, "task")]));
  const uniqueModels = [...new Set(aiIds.map((id) => agentById[id].model).filter(Boolean))];
  const llmVar = Object.fromEntries(uniqueModels.map((model) => [model, pyId(`llm_${model}`, "llm")]));

  const lines: string[] = [];

  // Header
  lines.push(`"""
CrewAI export — ${JSON.stringify(meta.name)}
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install crewai crewai-tools python-dotenv
"""
from __future__ import annotations
import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, ${isParallel ? "Process, LLM" : "Process, LLM"}
from crewai_tools import (
    FileReadTool, FileWriteTool, DirectoryReadTool, WebsiteSearchTool,
)

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local

`);

  // ── Tool registry ──────────────────────────────────────────────────────
  lines.push("# ── Tool registry ──────────────────────────────────────────────────────");
  lines.push("file_read    = FileReadTool()");
  lines.push("file_write   = FileWriteTool()");
  lines.push("dir_read     = DirectoryReadTool()");
  lines.push("web_search   = WebsiteSearchTool()");
  lines.push("");

  // ── LLM definitions ───────────────────────────────────────────────────
  if (uniqueModels.length > 0) {
    lines.push("# ── LLM definitions ────────────────────────────────────────────────────");
    uniqueModels.forEach((model) => {
      const provider = model.startsWith("claude") ? "anthropic" : "openai";
      lines.push(`${llmVar[model]} = LLM(model=${JSON.stringify(`${provider}/${model.replace(".", "-")}`)})`);
    });
    lines.push("");
  }

  // ── Agent definitions ──────────────────────────────────────────────────
  lines.push("# ── Agent definitions ──────────────────────────────────────────────────");
  aiIds.forEach((id) => {
    const a = agentById[id];
    const varName = agentVar[id];
    const modelVar = a.model ? llmVar[a.model] : "None";
    const roleMeta = ROLE_META[a.role];

    const systemPrompt = a.promptSource.type === "inline" && a.promptSource.content
      ? a.promptSource.content.slice(0, 300) + (a.promptSource.content.length > 300 ? "..." : "")
      : `${roleMeta.label} agent responsible for ${a.description || a.name}`;

    // Map tool permissions to CrewAI tools
    const toolVars: string[] = [];
    if (a.tools.some((t) => t.includes("read_file") || t.includes("fs.read"))) toolVars.push("file_read");
    if (a.tools.some((t) => t.includes("fs.write") || t.includes("write_file"))) toolVars.push("file_write");
    if (a.tools.some((t) => t.includes("list_files"))) toolVars.push("dir_read");
    if (a.tools.some((t) => t.includes("web_search") || t.includes("web_fetch"))) toolVars.push("web_search");

    lines.push(`${varName} = Agent(`);
    lines.push(indent(1, `role=${JSON.stringify(roleMeta.label)},`));
    lines.push(indent(1, `goal=${JSON.stringify(`${a.name}: ${a.description || systemPrompt.split(".")[0]}`)},`));
    lines.push(indent(1, `backstory=${JSON.stringify(systemPrompt)},`));
    if (toolVars.length > 0) {
      lines.push(indent(1, `tools=[${toolVars.join(", ")}],`));
    }
    if (a.model) {
      lines.push(indent(1, `llm=${modelVar},`));
    }
    lines.push(indent(1, `verbose=True,`));
    lines.push(indent(1, `allow_delegation=${a.role === AgentRole.Orchestrator ? "True" : "False"},`));
    lines.push(indent(1, `max_iter=${a.maxSteps},`));
    lines.push(")");
    lines.push("");
  });

  // ── Task definitions ───────────────────────────────────────────────────
  // Emitted in dependency order so `context` only names tasks defined above it
  // (Hook and Memory nodes get no task).
  const taskOrder = dependencyOrder(def).filter((id) => aiIds.includes(id));
  lines.push("# ── Task definitions ────────────────────────────────────────────────────");
  taskOrder.forEach((id, pos) => {
    const a = agentById[id];
    const definedTasks = taskOrder.slice(0, pos);

    // find context tasks (agents that feed into this one)
    const feedingAgents = connections
      .filter((c) =>
        c.targetAgentId === id && definedTasks.includes(c.sourceAgentId) &&
        c.edgeKind !== "feedback" && c.edgeKind !== "memory"
      )
      .map((c) => taskVar[c.sourceAgentId]);

    lines.push(`${taskVar[id]} = Task(`);
    lines.push(indent(1, `description=${JSON.stringify(`${a.name}: ${a.description || ROLE_META[a.role].label + " task"}`)},`));
    lines.push(indent(1, `expected_output=${JSON.stringify(`Structured output from ${a.name}`)},`));
    lines.push(indent(1, `agent=${agentVar[id]},`));
    if (feedingAgents.length > 0) {
      lines.push(indent(1, `context=[${feedingAgents.join(", ")}],`));
    }
    lines.push(")");
    lines.push("");
  });

  // ── Crew assembly ──────────────────────────────────────────────────────
  const allAgentVars = aiIds.map((id) => agentVar[id]);
  const allTaskVars  = taskOrder.map((id) => taskVar[id]);

  // Orchestrator is the manager if it exists
  const orchestrator = aiIds.find((id) => agentById[id].role === AgentRole.Orchestrator);

  lines.push("# ── Crew assembly ───────────────────────────────────────────────────────");
  lines.push("crew = Crew(");
  lines.push(indent(1, `agents=[${allAgentVars.join(", ")}],`));
  lines.push(indent(1, `tasks=[${allTaskVars.join(", ")}],`));
  lines.push(indent(1, `process=${process},`));
  if (isParallel && orchestrator) {
    lines.push(indent(1, `manager_agent=${agentVar[orchestrator]},`));
  }
  lines.push(indent(1, "verbose=True,"));
  lines.push(indent(1, "memory=True,"));
  lines.push(")");
  lines.push("");

  // ── Entry point ────────────────────────────────────────────────────────
  lines.push("# ── Entry point ────────────────────────────────────────────────────────");
  lines.push("if __name__ == '__main__':");
  lines.push(indent(1, "result = crew.kickoff(inputs={"));
  lines.push(indent(2, `"query": ${JSON.stringify(`Initial task for ${meta.name}`)}`));
  lines.push(indent(1, "})"));
  lines.push(indent(1, "print(result)"));

  return lines.join("\n");
}
