/**
 * LangGraph Python export — generates a runnable LangGraph StateGraph
 * that mirrors the visual workflow definition.
 */
import type { WorkflowDef } from "@/types/workflow";
import { AgentRole } from "@/types/agent";
import { ROLE_META } from "@/utils/nodeColors";

// Python's keyword.kwlist — none of these can be used as a variable name.
const PY_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
  "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
  "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
]);

// Names the template below binds or calls. Node names and state keys share this
// namespace too: LangGraph rejects a node named like a state key.
const RESERVED_NAMES = [
  "annotations", "os", "load_dotenv", "list", "open", "str", "print",
  "build_graph", "g", "checkpointer", "graph", "result", "messages",
];

/** Python identifier for `name`; empty, digit-leading or keyword results get `prefix`. */
function toPythonId(name: string, prefix: string): string {
  const id = name.toLowerCase().replace(/[\s\-]/g, "_").replace(/[^a-z0-9_]/g, "");
  if (!id) return prefix;
  return /^\d/.test(id) || PY_KEYWORDS.has(id) ? `${prefix}_${id}` : id;
}

function indent(n: number, s: string): string {
  return " ".repeat(n * 4) + s;
}

/** Hands out unique identifiers (numeric suffix on collision) so every reference uses one mapped name. */
function pythonIdAllocator(reserved: string[]): (name: string, prefix: string) => string {
  const used = new Set(reserved);
  return (name, prefix) => {
    const base = toPythonId(name, prefix);
    let id = base;
    for (let n = 2; used.has(id); n++) id = `${base}_${n}`;
    used.add(id);
    return id;
  };
}

/** User text inside a `#` comment must stay on one line. */
function comment(s: string): string {
  return s.replace(/[\r\n]+/g, " ");
}

export function generateLangGraph(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const agentById = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, a]));

  // Every Python name is allocated once, here, so all references agree.
  const pyId = pythonIdAllocator(RESERVED_NAMES);
  const nodeFn = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, pyId(a.name, "agent")]));
  const memKeys = [...new Set(agents.flatMap((a) => [...a.memoryRead, ...a.memoryWrite]))];
  const stateKey = Object.fromEntries(memKeys.map((k) => [k, pyId(k, "key")]));
  const uniqueModels = [...new Set(agents.filter((a) => a.model).map((a) => a.model))];
  const modelVars = Object.fromEntries(uniqueModels.map((model) => [model, pyId(model, "model")]));

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────
  lines.push(`"""
LangGraph export — ${JSON.stringify(meta.name)}
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install langgraph langchain-anthropic python-dotenv
"""
from __future__ import annotations
import os
from typing import TypedDict, Annotated, Sequence
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_anthropic import ChatAnthropic
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local
`);

  // ── State definition ───────────────────────────────────────────────────
  lines.push("# ── Shared workflow state ──────────────────────────────────────────────");
  lines.push("class WorkflowState(TypedDict):");
  lines.push(indent(1, "messages: Annotated[Sequence[BaseMessage], lambda a, b: list(a) + list(b)]"));
  memKeys.forEach((k) => {
    lines.push(indent(1, `${stateKey[k]}: str  # memory key: ${comment(k)}`));
  });
  lines.push("");

  // ── Model registry ─────────────────────────────────────────────────────
  lines.push("# ── Model registry ────────────────────────────────────────────────────");
  uniqueModels.forEach((model) => {
    const provider = model.startsWith("claude") ? "ChatAnthropic" : "ChatAnthropic";
    const apiModel = model.replace(".", "-");
    lines.push(`${modelVars[model]} = ${provider}(model=${JSON.stringify(apiModel)}, temperature=0.7)`);
  });
  lines.push("");

  // ── Node functions ─────────────────────────────────────────────────────
  lines.push("# ── Agent node functions ───────────────────────────────────────────────");
  agents.forEach((a, i) => {
    const fnName = nodeFn[`agent-${i}`];
    const modelVar = a.model ? modelVars[a.model] : "None";
    const roleMeta = ROLE_META[a.role];

    lines.push(`def ${fnName}(state: WorkflowState) -> WorkflowState:`);
    lines.push(indent(1, JSON.stringify(`${roleMeta.label}: ${a.description || a.name}`)));

    if (a.role === AgentRole.Memory) {
      lines.push(indent(1, "# Memory node — reads/writes persistent state"));
      a.memoryWrite.forEach((k) => {
        lines.push(indent(1, `# TODO: write to memory key '${comment(k)}'`));
      });
      lines.push(indent(1, "return state"));
    } else if (a.role === AgentRole.Hook) {
      lines.push(indent(1, "# Hook node — runs pre/post execution logic"));
      if (a.preHook) lines.push(indent(1, `# Pre-hook: ${comment(a.preHook.path)}`));
      if (a.postHook) lines.push(indent(1, `# Post-hook: ${comment(a.postHook.path)}`));
      lines.push(indent(1, "return state"));
    } else if (a.role === AgentRole.Gateway) {
      lines.push(indent(1, "# Gateway — pass-through node; its routes are plain edges in build_graph()"));
      lines.push(indent(1, `# Condition: ${comment(a.condition || "evaluate state")}`));
      lines.push(indent(1, "# TODO: route on the condition with g.add_conditional_edges instead"));
      lines.push(indent(1, 'return {"messages": []}  # no state change'));
    } else {
      if (a.promptSource.type === "inline" && a.promptSource.content) {
        lines.push(indent(1, `system_prompt = ${JSON.stringify(a.promptSource.content)}`));
      } else if (a.promptSource.type === "file") {
        lines.push(indent(1, `# Load prompt from file: ${comment(a.promptSource.path)}`));
        lines.push(indent(1, `with open(${JSON.stringify(a.promptSource.path)}, encoding="utf-8") as f:`));
        lines.push(indent(2, `system_prompt = f.read()`));
      } else {
        lines.push(indent(1, `system_prompt = ${JSON.stringify(`${a.name} agent`)}`));
      }
      lines.push("");
      if (a.model) {
        lines.push(indent(1, `response = ${modelVar}.invoke(`));
        lines.push(indent(2, `[{\"role\": \"system\", \"content\": system_prompt}] + list(state[\"messages\"])`));
        lines.push(indent(1, `)`));
        lines.push(indent(1, `return {\"messages\": [response]}`));
      } else {
        lines.push(indent(1, "# No model configured — pass through"));
        lines.push(indent(1, "return state"));
      }
    }
    lines.push("");
  });

  // ── Graph builder ──────────────────────────────────────────────────────
  lines.push("# ── Graph definition ───────────────────────────────────────────────────");
  lines.push("def build_graph() -> StateGraph:");
  lines.push(indent(1, "g = StateGraph(WorkflowState)"));
  lines.push("");

  // Add nodes
  agents.forEach((_, i) => {
    const fnName = nodeFn[`agent-${i}`];
    lines.push(indent(1, `g.add_node("${fnName}", ${fnName})`));
  });
  lines.push("");

  // Add edges
  connections.forEach((c) => {
    const src = agentById[c.sourceAgentId];
    const tgt = agentById[c.targetAgentId];
    if (!src || !tgt) return;
    const srcFn = nodeFn[c.sourceAgentId];
    const tgtFn = nodeFn[c.targetAgentId];

    if (c.edgeKind === "feedback") {
      // A plain LangGraph edge always fires, so an unconditional back edge would
      // loop until GraphRecursionError. Leave a conditional-edge template to wire.
      lines.push(indent(1, `# Feedback loop (${comment(c.label || "revise")}) — route back conditionally, e.g.:`));
      lines.push(indent(1, `# g.add_conditional_edges("${srcFn}", route_${srcFn}, {"revise": "${tgtFn}", "done": END})`));
    } else if (c.edgeKind === "memory") {
      lines.push(indent(1, `# Memory write: ${srcFn} → ${tgtFn}`));
    } else if (src.role === AgentRole.Gateway) {
      lines.push(indent(1, `g.add_edge("${srcFn}", "${tgtFn}")  # route: ${comment(c.label || "default")}`));
    } else {
      lines.push(indent(1, `g.add_edge("${srcFn}", "${tgtFn}")`));
    }
  });

  lines.push("");

  // Set entry point (first non-hook, non-memory node)
  const entry = agents.findIndex((a) => a.role !== AgentRole.Hook && a.role !== AgentRole.Memory);
  if (entry >= 0) {
    lines.push(indent(1, `g.set_entry_point("${nodeFn[`agent-${entry}`]}")`));
  }

  // Set terminal nodes (nodes with no outgoing non-feedback edges)
  const hasOutEdge = new Set(connections.filter((c) => c.edgeKind !== "feedback").map((c) => c.sourceAgentId));
  agents.forEach((_, i) => {
    if (!hasOutEdge.has(`agent-${i}`)) {
      lines.push(indent(1, `g.add_edge("${nodeFn[`agent-${i}`]}", END)`));
    }
  });

  lines.push("");
  lines.push(indent(1, "checkpointer = MemorySaver()"));
  lines.push(indent(1, "return g.compile(checkpointer=checkpointer)"));
  lines.push("");

  lines.push("");
  lines.push("# ── Entry point ────────────────────────────────────────────────────────");
  lines.push("if __name__ == '__main__':");
  lines.push(indent(1, "graph = build_graph()"));
  lines.push(indent(1, "result = graph.invoke("));
  lines.push(indent(2, `{"messages": [HumanMessage(content=${JSON.stringify(`Hello from ${meta.name}`)})]},`));
  lines.push(indent(2, `config={\"configurable\": {\"thread_id\": \"1\"}},`));
  lines.push(indent(1, ")"));
  lines.push(indent(1, "print(result)"));

  return lines.join("\n");
}
