/**
 * LangGraph Python export — generates a runnable LangGraph StateGraph
 * that mirrors the visual workflow definition.
 */
import type { WorkflowDef } from "@/types/workflow";
import { AgentRole } from "@/types/agent";
import { ROLE_META } from "@/utils/nodeColors";

function toPythonId(name: string): string {
  return name.toLowerCase().replace(/[\s\-]/g, "_").replace(/[^a-z0-9_]/g, "");
}

function indent(n: number, s: string): string {
  return " ".repeat(n * 4) + s;
}

export function generateLangGraph(def: WorkflowDef): string {
  const { meta, agents, connections } = def;
  const agentById = Object.fromEntries(agents.map((a, i) => [`agent-${i}`, a]));

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────
  lines.push(`"""
LangGraph export — ${meta.name}
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install langgraph langchain-anthropic python-dotenv
"""
from __future__ import annotations
import os
from typing import TypedDict, Annotated, Sequence
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_anthropic import ChatAnthropic
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local
`);

  // ── State definition ───────────────────────────────────────────────────
  lines.push("# ── Shared workflow state ──────────────────────────────────────────────");
  lines.push("class WorkflowState(TypedDict):");
  lines.push(indent(1, "messages: Annotated[Sequence[BaseMessage], lambda a, b: list(a) + list(b)]"));
  const memKeys = [...new Set(agents.flatMap((a) => [...a.memoryRead, ...a.memoryWrite]))];
  memKeys.forEach((k) => {
    lines.push(indent(1, `${toPythonId(k)}: str  # memory key: ${k}`));
  });
  lines.push("");

  // ── Model registry ─────────────────────────────────────────────────────
  const uniqueModels = [...new Set(agents.filter((a) => a.model).map((a) => a.model))];
  lines.push("# ── Model registry ────────────────────────────────────────────────────");
  uniqueModels.forEach((model) => {
    const varName = toPythonId(model);
    const provider = model.startsWith("claude") ? "ChatAnthropic" : "ChatAnthropic";
    const apiModel = model.replace(".", "-");
    lines.push(`${varName} = ${provider}(model="${apiModel}", temperature=0.7)`);
  });
  lines.push("");

  // ── Node functions ─────────────────────────────────────────────────────
  lines.push("# ── Agent node functions ───────────────────────────────────────────────");
  agents.forEach((a) => {
    const fnName = toPythonId(a.name);
    const modelVar = a.model ? toPythonId(a.model) : "None";
    const roleMeta = ROLE_META[a.role];

    lines.push(`def ${fnName}(state: WorkflowState) -> WorkflowState:`);
    lines.push(indent(1, `"""${roleMeta.label}: ${a.description || a.name}"""`));

    if (a.role === AgentRole.Memory) {
      lines.push(indent(1, "# Memory node — reads/writes persistent state"));
      a.memoryWrite.forEach((k) => {
        lines.push(indent(1, `# TODO: write to memory key '${k}'`));
      });
      lines.push(indent(1, "return state"));
    } else if (a.role === AgentRole.Hook) {
      lines.push(indent(1, "# Hook node — runs pre/post execution logic"));
      if (a.preHook) lines.push(indent(1, f`# Pre-hook: ${a.preHook.path}`));
      if (a.postHook) lines.push(indent(1, f`# Post-hook: ${a.postHook.path}`));
      lines.push(indent(1, "return state"));
    } else if (a.role === AgentRole.Gateway) {
      lines.push(indent(1, "# Gateway — routes based on condition"));
      lines.push(indent(1, f`# Condition: ${a.condition || 'evaluate state'}`));
      lines.push(indent(1, "# This function returns routing key, not state"));
      lines.push(indent(1, "last_msg = state['messages'][-1] if state['messages'] else None"));
      lines.push(indent(1, "# TODO: implement routing logic"));
      lines.push(indent(1, "return 'default'  # return the name of the next node"));
    } else {
      if (a.promptSource.type === "inline" && a.promptSource.content) {
        const escaped = a.promptSource.content.replace(/"""/g, "'''");
        lines.push(indent(1, `system_prompt = """${escaped}"""`));
      } else if (a.promptSource.type === "file") {
        lines.push(indent(1, `# Load prompt from file: ${a.promptSource.path}`));
        lines.push(indent(1, `with open("${a.promptSource.path}") as f:`));
        lines.push(indent(2, `system_prompt = f.read()`));
      } else {
        lines.push(indent(1, `system_prompt = "${a.name} agent"`));
      }
      lines.push("");
      if (a.model) {
        lines.push(indent(1, `response = ${modelVar}.invoke(`));
        lines.push(indent(2, `[{\"role\": \"system\", \"content\": system_prompt}] + list(state[\"messages\"])`));
        lines.push(indent(1, `)`));
        lines.push(indent(1, `return {\"messages\": [response]}`));
      } else {
        lines.push(indent(1, "# No model configured — pass through"));
        lines.push(indent(1, "return state"));
      }
    }
    lines.push("");
  });

  // Fix template literals (TS `f` is not Python)
  const fixedLines = lines.map((l) => l.replace(/f`(.*?)`/g, (_, s) => `"${s}"`));

  // ── Graph builder ──────────────────────────────────────────────────────
  fixedLines.push("# ── Graph definition ───────────────────────────────────────────────────");
  fixedLines.push("def build_graph() -> StateGraph:");
  fixedLines.push(indent(1, "g = StateGraph(WorkflowState)"));
  fixedLines.push("");

  // Add nodes
  agents.forEach((a) => {
    const fnName = toPythonId(a.name);
    if (a.role !== AgentRole.Gateway) {
      fixedLines.push(indent(1, `g.add_node("${fnName}", ${fnName})`));
    }
  });
  fixedLines.push("");

  // Add edges
  connections.forEach((c) => {
    const src = agentById[c.sourceAgentId];
    const tgt = agentById[c.targetAgentId];
    if (!src || !tgt) return;
    const srcFn = toPythonId(src.name);
    const tgtFn = toPythonId(tgt.name);

    if (src.role === AgentRole.Gateway) {
      // conditional edge from gateway's parent
      fixedLines.push(indent(1, `# Gateway routing: ${src.name} → ${tgt.name}${c.label ? ` (${c.label})` : ""}`));
      fixedLines.push(indent(1, `# g.add_conditional_edges("...", ${srcFn}, {"${c.label || "default"}": "${tgtFn}"})`));
    } else if (c.edgeKind === "feedback") {
      fixedLines.push(indent(1, `g.add_edge("${tgtFn}", "${srcFn}")  # feedback loop`));
    } else if (c.edgeKind === "memory") {
      fixedLines.push(indent(1, `# Memory write: ${srcFn} → ${tgtFn}`));
    } else {
      fixedLines.push(indent(1, `g.add_edge("${srcFn}", "${tgtFn}")`));
    }
  });

  fixedLines.push("");

  // Set entry point (first non-hook, non-memory node)
  const entry = agents.find((a) => a.role !== AgentRole.Hook && a.role !== AgentRole.Memory);
  if (entry) {
    fixedLines.push(indent(1, `g.set_entry_point("${toPythonId(entry.name)}")`));
  }

  // Set terminal nodes (nodes with no outgoing non-feedback edges)
  const hasOutEdge = new Set(connections.filter((c) => c.edgeKind !== "feedback").map((c) => c.sourceAgentId));
  agents.forEach((a, i) => {
    if (!hasOutEdge.has(`agent-${i}`) && a.role !== AgentRole.Gateway) {
      fixedLines.push(indent(1, `g.add_edge("${toPythonId(a.name)}", END)`));
    }
  });

  fixedLines.push("");
  fixedLines.push(indent(1, "checkpointer = MemorySaver()"));
  fixedLines.push(indent(1, "return g.compile(checkpointer=checkpointer)"));
  fixedLines.push("");

  fixedLines.push("");
  fixedLines.push("# ── Entry point ────────────────────────────────────────────────────────");
  fixedLines.push("if __name__ == '__main__':");
  fixedLines.push(indent(1, "graph = build_graph()"));
  fixedLines.push(indent(1, "result = graph.invoke("));
  fixedLines.push(indent(2, `{\"messages\": [HumanMessage(content=\"Hello from ${meta.name}\")]},`));
  fixedLines.push(indent(2, `config={\"configurable\": {\"thread_id\": \"1\"}},`));
  fixedLines.push(indent(1, ")"));
  fixedLines.push(indent(1, "print(result)"));

  return fixedLines.join("\n");
}

// Helper for Python-style f-strings in the generator (not actual f-strings)
function f(strings: TemplateStringsArray, ...values: unknown[]): string {
  return strings.reduce((acc, str, i) => acc + str + (values[i] ?? ""), "");
}
