"""
CrewAI export — Spec to PR
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install crewai crewai-tools python-dotenv
"""
from __future__ import annotations
import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from crewai_tools import (
    FileReadTool, FileWriteTool, DirectoryReadTool, WebsiteSearchTool,
)

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local


# ── Tool registry ──────────────────────────────────────────────────────
file_read    = FileReadTool()
file_write   = FileWriteTool()
dir_read     = DirectoryReadTool()
web_search   = WebsiteSearchTool()

# ── LLM definitions ────────────────────────────────────────────────────
llm_claude_opus_46 = LLM(model="anthropic/claude-opus-4-6")
llm_claude_sonnet_46 = LLM(model="anthropic/claude-sonnet-4-6")
llm_claude_haiku_45 = LLM(model="anthropic/claude-haiku-4-5")

# ── Agent definitions ──────────────────────────────────────────────────
spec_writer = Agent(
    role="Orchestrator",
    goal="Spec Writer: Expands the user's feature request into a comprehensive spec. Enumerates ≥ 10 testable requirements. Each starts as FAIL.
",
    backstory="""You are the Spec Writer. Given a feature request:
1. Write a comprehensive specification with ≥ 10 testable requirements.
2. Format each requirement as: "REQ-N: [description] — Status: FAIL".
3. Save the spec to .harness/spec.md using fs.write.
4. Return the path to the spec file.
""",
    tools=[file_write],
    llm=llm_claude_opus_46,
    verbose=True,
    allow_delegation=true,
    max_iter=10,
)

planner = Agent(
    role="Worker",
    goal="Planner: Reads the spec and produces a depth-first task list. Each task touches ≤ 2 files. Stops and asks on first ambiguity.
",
    backstory="""You are the Planner. Read the spec from .harness/spec.md:
1. Produce a depth-first task list. Each task must touch ≤ 2 files.
2. Write the task list to .harness/tasks.md.
3. If anything is ambiguous, stop and output: {"status": "needs_clarification", "question": "..."}.
4. Otherwise output: {"status...""",
    tools=[file_read, file_write],
    llm=llm_claude_sonnet_46,
    verbose=True,
    allow_delegation=false,
    max_iter=15,
)

implementer = Agent(
    role="Worker",
    goal="Implementer: Executes tasks one at a time. Runs tests after each change. Never marks a task complete without a green test run.
",
    backstory="""You are the Implementer. Work through .harness/tasks.md one task at a time:
1. Read the next PENDING task.
2. Implement the change (edit files using fs.write).
3. Run tests: bash("npm test" or "cargo test").
4. Only mark the task DONE if tests are green.
5. If a test is red after 2 attempts, mark th...""",
    tools=[file_read, file_write, dir_read],
    llm=llm_claude_sonnet_46,
    verbose=True,
    allow_delegation=false,
    max_iter=40,
)

verifier = Agent(
    role="Critic",
    goal="Verifier: Runs the full test suite, linter, and type-checker. Also runs end-to-end tests via Puppeteer. Blocks on any red.
",
    backstory="""You are the Verifier. Run the full quality gate:
1. bash("npm run lint") — must exit 0.
2. bash("npm run typecheck") — must exit 0.
3. bash("npm test") — all tests must be green.
4. puppeteer("run e2e suite") — all e2e tests must pass.
If all pass: {"verdict": "PASS"}.
If any fail: {"verdict": "REVI...""",
    tools=[file_read],
    llm=llm_claude_opus_46,
    verbose=True,
    allow_delegation=false,
    max_iter=10,
)

reporter = Agent(
    role="Aggregator",
    goal="Reporter: Summarizes the diff, test results, and any caveats. Produces a PR description in the team template format.
",
    backstory="""You are the Reporter. Produce a pull-request description:
1. Read the git diff: git("diff main..HEAD").
2. Read the test results from memory.
3. Write a PR description to .harness/pr-description.md matching this template:
   ## Summary
   ## Changes
   ## Test results
   ## Caveats
4. Output the pat...""",
    tools=[file_read, file_write],
    llm=llm_claude_haiku_45,
    verbose=True,
    allow_delegation=false,
    max_iter=5,
)

# ── Task definitions ────────────────────────────────────────────────────
task_spec_writer = Task(
    description="Spec Writer: Expands the user's feature request into a comprehensive spec. Enumerates ≥ 10 testable requirements. Each starts as FAIL.
",
    expected_output="Structured output from Spec Writer",
    agent=spec_writer,
)

task_planner = Task(
    description="Planner: Reads the spec and produces a depth-first task list. Each task touches ≤ 2 files. Stops and asks on first ambiguity.
",
    expected_output="Structured output from Planner",
    agent=planner,
    context=[task_spec_writer],
)

task_implementer = Task(
    description="Implementer: Executes tasks one at a time. Runs tests after each change. Never marks a task complete without a green test run.
",
    expected_output="Structured output from Implementer",
    agent=implementer,
    context=[task_planner],
)

task_verifier = Task(
    description="Verifier: Runs the full test suite, linter, and type-checker. Also runs end-to-end tests via Puppeteer. Blocks on any red.
",
    expected_output="Structured output from Verifier",
    agent=verifier,
    context=[task_implementer],
)

task_reporter = Task(
    description="Reporter: Summarizes the diff, test results, and any caveats. Produces a PR description in the team template format.
",
    expected_output="Structured output from Reporter",
    agent=reporter,
    context=[task_verifier],
)

# ── Crew assembly ───────────────────────────────────────────────────────
crew = Crew(
    agents=[spec_writer, planner, implementer, verifier, reporter],
    tasks=[task_spec_writer, task_planner, task_implementer, task_verifier, task_reporter],
    process=Process.hierarchical,
    manager_agent=spec_writer,
    verbose=True,
    memory=True,
)

# ── Entry point ────────────────────────────────────────────────────────
if __name__ == '__main__':
    result = crew.kickoff(inputs={
        "query": "Initial task for Spec to PR"
    })
    print(result)