"""
LangGraph export — Spec to PR
Generated by Harness Studio. Edit the harness YAML, then regenerate.

Requirements:
    pip install langgraph langchain-anthropic python-dotenv
"""
from __future__ import annotations
import os
from typing import TypedDict, Annotated, Sequence
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_anthropic import ChatAnthropic
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()  # loads ANTHROPIC_API_KEY from .env.local

# ── Shared workflow state ──────────────────────────────────────────────
class WorkflowState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], lambda a, b: list(a) + list(b)]
    spec_path: str  # memory key: spec-path
    task_list_path: str  # memory key: task-list-path
    impl_status: str  # memory key: impl-status
    verify_verdict: str  # memory key: verify-verdict
    pr_path: str  # memory key: pr-path

# ── Model registry ────────────────────────────────────────────────────
claude_opus_46 = ChatAnthropic(model="claude-opus-4-6", temperature=0.7)
claude_sonnet_46 = ChatAnthropic(model="claude-sonnet-4-6", temperature=0.7)
claude_haiku_45 = ChatAnthropic(model="claude-haiku-4-5", temperature=0.7)

# ── Agent node functions ───────────────────────────────────────────────
def spec_writer(state: WorkflowState) -> WorkflowState:
    """Orchestrator: Expands the user's feature request into a comprehensive spec. Enumerates ≥ 10 testable requirements. Each starts as FAIL.
"""
    system_prompt = """You are the Spec Writer. Given a feature request:
1. Write a comprehensive specification with ≥ 10 testable requirements.
2. Format each requirement as: "REQ-N: [description] — Status: FAIL".
3. Save the spec to .harness/spec.md using fs.write.
4. Return the path to the spec file.
"""

    response = claude_opus_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def planner(state: WorkflowState) -> WorkflowState:
    """Worker: Reads the spec and produces a depth-first task list. Each task touches ≤ 2 files. Stops and asks on first ambiguity.
"""
    system_prompt = """You are the Planner. Read the spec from .harness/spec.md:
1. Produce a depth-first task list. Each task must touch ≤ 2 files.
2. Write the task list to .harness/tasks.md.
3. If anything is ambiguous, stop and output: {"status": "needs_clarification", "question": "..."}.
4. Otherwise output: {"status": "ready", "task_count": N}.
"""

    response = claude_sonnet_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def implementer(state: WorkflowState) -> WorkflowState:
    """Worker: Executes tasks one at a time. Runs tests after each change. Never marks a task complete without a green test run.
"""
    system_prompt = """You are the Implementer. Work through .harness/tasks.md one task at a time:
1. Read the next PENDING task.
2. Implement the change (edit files using fs.write).
3. Run tests: bash("npm test" or "cargo test").
4. Only mark the task DONE if tests are green.
5. If a test is red after 2 attempts, mark the task BLOCKED and stop.
"""

    response = claude_sonnet_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def verifier(state: WorkflowState) -> WorkflowState:
    """Critic: Runs the full test suite, linter, and type-checker. Also runs end-to-end tests via Puppeteer. Blocks on any red.
"""
    system_prompt = """You are the Verifier. Run the full quality gate:
1. bash("npm run lint") — must exit 0.
2. bash("npm run typecheck") — must exit 0.
3. bash("npm test") — all tests must be green.
4. puppeteer("run e2e suite") — all e2e tests must pass.
If all pass: {"verdict": "PASS"}.
If any fail: {"verdict": "REVISE", "failures": [...log lines...]}.
"""

    response = claude_opus_46.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

def reporter(state: WorkflowState) -> WorkflowState:
    """Aggregator: Summarizes the diff, test results, and any caveats. Produces a PR description in the team template format.
"""
    system_prompt = """You are the Reporter. Produce a pull-request description:
1. Read the git diff: git("diff main..HEAD").
2. Read the test results from memory.
3. Write a PR description to .harness/pr-description.md matching this template:
   ## Summary
   ## Changes
   ## Test results
   ## Caveats
4. Output the path to the PR description file.
"""

    response = claude_haiku_45.invoke(
        [{"role": "system", "content": system_prompt}] + list(state["messages"])
    )
    return {"messages": [response]}

# ── Graph definition ───────────────────────────────────────────────────
def build_graph() -> StateGraph:
    g = StateGraph(WorkflowState)

    g.add_node("spec_writer", spec_writer)
    g.add_node("planner", planner)
    g.add_node("implementer", implementer)
    g.add_node("verifier", verifier)
    g.add_node("reporter", reporter)

    g.add_edge("spec_writer", "planner")
    g.add_edge("planner", "implementer")
    g.add_edge("implementer", "verifier")
    g.add_edge("implementer", "verifier")  # feedback loop
    g.add_edge("verifier", "reporter")

    g.set_entry_point("spec_writer")
    g.add_edge("reporter", END)

    checkpointer = MemorySaver()
    return g.compile(checkpointer=checkpointer)


# ── Entry point ────────────────────────────────────────────────────────
if __name__ == '__main__':
    graph = build_graph()
    result = graph.invoke(
        {"messages": [HumanMessage(content="Hello from Spec to PR")]},
        config={"configurable": {"thread_id": "1"}},
    )
    print(result)